### ISSUE TITLE
[Task] Fully support requirement suggestion

### ISSUE THREAD

**Issue by malusamayo** [malusamayo/zeno-req-prompt#2]
We currently use [mock-up code](https://github.com/malusamayo/zeno-req-prompt/blob/dev/zeno/backend.py#L1110) for requirement suggestion. Replace it with LLM-based suggestion. 

For the suggestion, sample 5 input/output pairs (if output is not available, just use inputs) for LLM to look at.

Once the backend is complete, trigger requirement suggestions after prompt updates / run.

**Comment by cassandrashi** [comment]
pushed the code to dev branch

**Comment by malusamayo** [comment]
One additional feature we can add:
- For each suggested requirement, ask LLM to output a related example, and also add the example to the requirement
