### ISSUE TITLE
[Task] Change how user interacts with examples for requirements

### ISSUE THREAD

**Issue by malusamayo** [malusamayo/zeno-req-prompt#4]
1. Replace thumbs up / down with a "+" button. The button triggers a new pop-up window, asking for 
    - related requirements -- user can add a new requirement here
    - use the example as positive or negative example
    - rationales (model filled but can be edited)
2. Move thumbs down on evaluator into rationales & add the example as a positive example

**Comment by cassandrashi** [comment]
pushed the code to dev branch

**Comment by malusamayo** [comment]
On user experience:
- The new pop-up window should appear under the thumbs up / down (look at how we do tooltips' positions or check absolute positions) and should go away when click outside like all other pop-up windows
- When thumbs up, it is a bit unclear what users can do with the requirements -- maybe add hints like "select related requirements", and use checkbox in each requirement cell for it (instead of color changes)
- When thumbs down, it is also unclear what users can do with the two new buttons. We can have one simple pop-up window for both: Add an input cell under existing requirements (like what we do in the left-side panel)
- For thumbs up / down, there should be a feedback textbox, which can be prefilled by model rationales but can be edited by users.

**Comment by cassandrashi** [comment]
Code pushed to dev
1. Pop-up window position: The space under the thumbs up/down icons was insufficient to display the entire pop-up window, as it contains a full list of requirements. I preserved the pop-up at the center of the screen, similar to how we display the requirement details. The pop-up now closes when clicking outside, just like the other pop-up windows.
2. Checkbox implementation and example tracking: Added hints like "Select related requirements" and replaced color changes with checkboxes in each requirement cell. I also created a store variable to track whether an example is checked for any requirement. Now, when users click on the icon, the checking status in the window shows which examples belong to which requirements. Additionally, I implemented a backend function to remove examples when users uncheck them.
3. Rationale inclusion: The rationale is now included as part of the example in the backend.

**Comment by malusamayo** [comment]
For the pop-up window position, we should still place them under (next to) thumbs down/up. We can still overlay them on the top. Right now it is just a bit confusing when users click on thumbs up/down, sometimes the example text will be blocked by the new window

**Comment by malusamayo** [comment]
For example tracking, we might want to test the implementation a bit. Some existing bugs I observed:
- Thumbs-up / thumbs-down for one example are sharing the same set of checked examples 
- When an example for *one prompt version* is checked for one requirement, the examples for newer versions are also checked. Ideally, we should be able to distinguish examples from _which_ run contribute to the requirement.

**Comment by malusamayo** [comment]
Per today's discussion, we need to re-think what operations in the example space are needed for updating requirements:

For each example, we will have a list of evaluation results for all requirements
- If the example is good/bad in a new way that is not captured by the requirements, users can add a new requirement
- If the example is good for one requirement but other examples are bad, users can add it to that requirement for better compilation
  -  Similarly if the example is bad, users can add it as counter-examples?
- If the example is good/bad for one requirement but the evaluator is wrong, users can add it to that requirement for better validation
